#!/bin/bash


cat <<- EOF
## Project name
> 

### Resources:
* [ 

### Description of what each file shows:
 

### Environment
* Language: Python 3.4.3, C 89, Bash scripts  
* OS: Ubuntu 14.04 LTS
* Compiler: python3, gcc 4.8.4  
* Container: Docker  
* Web Server: Apache  
* Style guidelines: [Shellscript for Bash](https://github.com/koalaman/shellcheck) || [PEP 8 (version 1.7) for Python 3.5](https://www.python.org/dev/peps/pep-0008/) || [Google Style Python Docstrings](http://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html) || [Betty style for C89](https://github.com/holbertonschool/Betty/wiki) || [Javascript Standard](https://standardjs.com/rules.html) || [Javascript Semistandard](https://github.com/Flet/semistandard) || [Airbnb Javascript Style Guide](https://github.com/airbnb/javascript)

---
### Authors
Melissa Ng [![M](https://upload.wikimedia.org/wikipedia/fr/thumb/c/c8/Twitter_Bird.svg/30px-Twitter_Bird.svg.png)](https://twitter.com/MelissaNg__)
EOF

# POTENTIAL README CATEGORIES
### How to Install/Use
### License

# MARKUP SYNTAX FOR IMAGES
[![M](image.png)](optional website link)
